# Generated by Django 4.2.9 on 2024-02-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_lesson_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishclass',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
