# Generated by Django 4.2.9 on 2024-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_englishclass_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='google_meet_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='online_meeting_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='meeting_link',
            field=models.URLField(blank=True, null=True, verbose_name='Meeting Link'),
        ),
    ]
