# Generated by Django 4.2.9 on 2024-02-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_lesson_google_meet_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishclass',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
