# Generated by Django 4.2.9 on 2024-03-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_englishclass_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.BinaryField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
