# Generated by Django 4.2.9 on 2024-03-18 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_remove_material_english_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleCalendarEvent',
        ),
    ]
