# heso/urls.py

from django.contrib import admin
from django.urls import path, include
from users.views import home

"""
Main URL configuration for the HESO project.

This module routes URLs to their corresponding views as defined in the project's applications.
- The root URL is redirected to the home view, providing a landing page for authenticated users.
- The admin route is reserved for the Django admin interface, a powerful and autogenerated tool for site management.
- URLs prefixed with 'schedule/' are routed to the scheduling application, handling all scheduling-related views.
- URLs prefixed with 'users/' are routed to the user management application, handling authentication, registration, and user profiles.
"""

urlpatterns = [
    path("", home, name="home"),  # Redirects to the home view
    path("admin/", admin.site.urls),  # Admin interface
    path("schedule/", include("scheduling.urls")),  # Scheduling application
    path("users/", include("users.urls")),  # User management application
]
